### ISSUE TITLE
First pass at random gen mob path

### ISSUE THREAD

**Issue by Wilky0** [Wilky0/ChibisInSpace#7]
Set up a basic form of random generation for the path of the mobs to see if this is a viable approach. Start point can be random along the top of the screen and the player's base could possibly be a random position to? thoughts on that?

**Comment by MatBastiaens** [comment]
I think that will depend on how we want the game to look. Are they gonna follow a a pathway or is it going to be an open plane where you can decide how to build wherever / whenever?

**Comment by Wilky0** [comment]
Well Im imagining currently the random gen will create a pathway for the mobs to follow, you can choose if that path is represented with an image or not. The other option is you could have them all have their own randomly generated paths but like you said before means you cant plan out the most efficient tower placement cos you wouldn't know where they are going. There is also the option of maybe genning more than one path and make it random which one the mob follows

**Comment by Wilky0** [comment]
First pass of gen added in merge #12
